### PR TITLE
Use non-atomic pointer for dynamic dispatch when atomic is not available

### LINKED ISSUE #90: Make atomic_ptr optional for active_implementation?
When cross-compiling `simdutf` targetting `wasm32-wasi`, due to lack of `<atomics>` and such, compilation will fail. Would you accept a patch that opt out of `atomic_ptr` on platforms that lack threads and atomics?

### PR DESCRIPTION
**Pull request by TerrorJack**
Closes #90

### CODE REVIEW

File: include/simdutf/compiler_check.h [hunk 1]
```diff
@@ -32,4 +32,10 @@
 #error simdutf requires a compiler compliant with the C++11 standard
 #endif
 
+#if defined(SIMDUTF_CPLUSPLUS17)
+#if !__has_include(<atomic>)
```
Comment (lemire) [inline include/simdutf/compiler_check.h:36]: Ok. So if atomic is not found, then we know for sure that it cannot be threaded... correct?

**Comment by WojciechMula** [comment]
> @WojciechMula Would you review this?

Sure, I will take a look.

**Comment by WojciechMula** [comment]
@TerrorJack @lemire This looks much better than the initial proposal, thanks a lot. I'm not insisting on creating a dummy atomic class, that single `#ifdef` looks fine. I'm for merging this PR.

I have just run CI to see if the PR passes.
